### ISSUE TITLE
Error: can't resolve reference http://json-schema.org/draft-06/schema# from id #

### ISSUE THREAD

**Issue by amosyuen** [epoberezkin/ajv-merge-patch#17]
I'm trying to use the library in the browser compiled by babel and webpack. When I run this code:
```js
import Ajv from 'ajv';
import ajvMergePatch from 'ajv-merge-patch';

const ajvInstance = new Ajv({});
ajvMergePatch(ajvInstance);
```

I get the following error:
```
bootstrap 436b72c1f8f84619e6c0:802 Error: can't resolve reference http://json-schema.org/draft-06/schema# from id #
    at Object.generate_ref [as code] (http://localhost/1.js:8952:22)
    at Object.generate_validate [as validate] (http://localhost/1.js:9645:37)
    at Object.generate_anyOf [as code] (http://localhost/1.js:7185:27)
    at Object.generate_validate [as validate] (http://localhost/1.js:9718:37)
    at Object.generate_properties [as code] (http://localhost/1.js:8636:26)
    at generate_validate (http://localhost/1.js:9718:37)
    at localCompile (http://localhost/1.js:5573:22)
    at Ajv.compile (http://localhost/1.js:5541:13)
    at _compile (http://localhost/1.js:4840:29)
    at Ajv.compile (http://localhost/1.js:4626:34)
    at Ajv.addKeyword (http://localhost/1.js:9930:40)
    at webpackJsonp../lib/node_modules/ajv-merge-patch/keywords/add_keyword.js.module.exports (http://localhost/1.js:2230:7)
    at webpackJsonp../lib/node_modules/ajv-merge-patch/keywords/merge.js.module.exports (http://localhost/1.js:2288:3)
    at addKeywords (http://localhost/1.js:2214:3)
```

**Comment by epoberezkin** [comment]
Unless you are using some old Ajv version that doesn't have draft-06 meta-schema, I suspect it is the same issue as https://github.com/epoberezkin/ajv/issues/547

If it's neither please resubmit the issue using [this template](https://github.com/epoberezkin/ajv/issues/new?labels=compatibility&body=**The%20version%20of%20Ajv%20you%20are%20using**%0A%0A**The%20environment%20you%20have%20the%20problem%20with.**%0A%0A**Your%20code%20(please%20make%20it%20as%20small%20as%20possible%20to%20reproduce%20the%20issue).**%0A%0A**If%20your%20issue%20is%20in%20the%20browser,%20please%20list%20the%20other%20packages%20loaded%20in%20the%20page%20in%20the%20order%20they%20are%20loaded.%20Please%20check%20if%20the%20issue%20gets%20resolved%20(or%20results%20change)%20if%20you%20move%20Ajv%20bundle%20closer%20to%20the%20top.**%0A%0A**Results%20in%20node.js%20v6.**%0A%0A**Results%20and%20error%20messages%20in%20your%20platform.**%0A%0A)
